# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rahul Chajwa
email: rchajwa@stanford.edu
description: >-
#  I investigate self-organization, adaptation, learning,
#  and emergence in soft condensed matter and biological systems.

baseurl: "" # the subpath of your site, e.g. /blog
url: ""     # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: rahulchajwa
scholar_url: "https://scholar.google.com/citations?user=CvTCP7QAAAAJ&hl=en"
linkedin: rahul-chajwa-b695a112a
orcid: "https://orcid.org/0000-0002-6488-1834" 
theme: minima

plugins:
  - jekyll-feed

social_links:
  google_scholar: "https://scholar.google.com/citations?user=CvTCP7QAAAAJ&hl=en"
  linkedin: rahul-chajwa-b695a112a
  orcid: "https://orcid.org/0000-0002-6488-1834"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#title: Rahul Chajwa
#description: Physics of living systems, Soft Condensed Matter, The biological pump
url: "https://rahulchajwa.github.io"
markdown: kramdown
kramdown:
  math_engine: katex

plugins:
  - jekyll-feed

